spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username: root
    password:
    hikari:
      idle-timeout: 180000
      minimum-idle: 5
      maximum-pool-size: 1000
      connection-timeout: 30000
      max-lifetime: 180000
      auto-commit: true
mybatis:
  config-location: classpath:mybatis.xml
logging:
    level:
      com.hw.mapper: debug
debug: true
server:
  port: 7777
